### ISSUE TITLE
AWS Transfer Family endpoint type matrix : Incorrect Headers

### ISSUE THREAD

**Issue by srikars** [awsdocs/aws-transfer-user-guide#2]
aws-transfer-user-guide/doc_source/create-server.md
Line 58. 

In "Endpoint type matrix" table: it looks like "VPC - Internet" and "VPC - Internal" headings are interchanged. The characteristics below do not match the headings/title.
Can you please check and rectify it? Thank you.

**Comment by aws-smarcus** [comment]
Thank you for catching this. I have updated the public-facing user guide at https://docs.aws.amazon.com/transfer/latest/userguide/create-server.html#endpoint-matrix, and have also updated the affected file here on GitHub.
