### ISSUE TITLE
A template in this user guide doesn't work

### ISSUE THREAD

**Issue by Kainanchen** [awsdocs/aws-transfer-user-guide#3]
Under the section "Lambda function templates",

I tried "Classic (Cognito) stack template" When I upload this template to Cloudformation, it gives an error:
CreateServer error.

Could you update this template or figure out if I did something wrong.

Best regards,

Kainan

**Comment by aws-smarcus** [comment]
Thank you for identifying this issue. We are going to fix the template. But in the meantime, replace the following:
`Fn::If:`
    `- CreateServer`
   ` - Fn::GetAtt: TransferServer.Arn`
   ` - Fn::Sub: arn:${AWS::Partition}:transfer:${AWS::Region}:${AWS::AccountId}:server/*`

with this:
`- Fn::GetAtt: TransferServer.Arn`
