### ISSUE TITLE
Issue for the New workflow step for the Decrypt file type

### ISSUE THREAD

**Issue by ryanlin-tech** [awsdocs/aws-transfer-user-guide#5]
About the New workflow step for the Decrypt file type, I follow the steps in the docs, but the decryption function is not working. I can't find any tutorial about this new feature in the community. Could you double-check the steps for it? or make a short video for the demo?

**Comment by aws-smarcus** [comment]
Hi Ryan,

Thank you for reaching out. I understand your issue, and have added your request onto my to-do list. I will create a tutorial, and possibly a video.

Scott Marcus
Technical Writer
AWS, Transfer Family

From: Ryan Lin ***@***.***>
Sent: Sunday, January 15, 2023 8:23 AM
To: awsdocs/aws-transfer-user-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [awsdocs/aws-transfer-user-guide] Issue for the New workflow step for the Decrypt file type (Issue #5)


About the New workflow step for the Decrypt file type, I follow the steps in the docs, but the decryption function is not working. I can't find any tutorial about this new feature in the community. Could you double-check the steps for it? or make a short video for the demo?

-

**Comment by tm03068** [comment]
+1 for this, following the tutorial does not result in a successful file decryption. 

Which leads me to my next question - ~~What is the best way to troubleshoot workflows?~~ Managed workflows associated with Transfer Family servers have Cloudwatch Log Groups for logging output.

Getting this from following the tutorial to a T. There may be some specific options when encrypting the file that are needed
```
"type": "StepErrored",
    "details": {
        "errorType": "BAD_REQUEST",
        "errorMessage": "Encryption algorithm not found in encrypted data",
        "stepType": "DECRYPT",
        "stepName": "decrypt"
    },
```

**Comment by aws-smarcus** [comment]
Hi https://github.com/tm03068. Can you provide some more details? For example, which key type are you using? Which program did you use to encrypt your file -- and which options? Also, if you would like, you could create a ticket for AWS Transfer Family (https://support.console.aws.amazon.com/support/home/).

**Comment by tm03068** [comment]
Hey Scott, Sure I have followed the tutorial using the same file encryption commands listed. I recreated the key to use RSA as opposed to the default which was ed25519 (I previously did not see this as an unsupported option on the Key Management page of the Transfer Family documentation) and I have been able to proceed past that specific error I mentioned above. ~~I will open a support ticket for further troubleshooting since the decryption step seems to be hanging~~. 

Thank you for your response

update: I incorrectly stored the PGP private key in Secrets Manager. Fixing this corrected my issue. Thanks again Scott for the tutorial!

**Comment by aws-smarcus** [comment]
That's great news: I'm glad you were successful, and that the documentation was helpful.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
